version: '3.8'

services:
  tailscale:
    image: tailscale/tailscale:latest
    # Container name will be 'tailnord-tailscale-myinstance' (based on .env)
    container_name: tailnord-tailscale-${INSTANCE_NAME}
    hostname: tailnord-tailscale
    #command: [
    #  '/scripts/tailscale_up.sh'
    #]
    user: root
    restart: always
    volumes:
      - "/dev/net/tun:/dev/net/tun"
      - "./tailscale/state:/var/lib/tailscale"
      - "./tailscale/scripts:/scripts"
    environment:
      - TAILSCALE_UP_LOGIN_SERVER=${TAILSCALE_UP_LOGIN_SERVER}
      - IP_NORDVPN=${IP_NORDVPN} # NordVPN container IP for scripts
      - INSTANCE_NAME=${INSTANCE_NAME} # Passed for script usage or identification
      # - IP_SUBNET=${IP_SUBNET} # Uncomment if needed in tailscale_up.sh
    cap_add:
      - net_admin
      - sys_module
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    networks:
      tailnord-net:
        ipv4_address: ${IP_TAILSCALE}

  nordvpn:
    build:
      context: nordvpn
    # Container name will be 'tailnord-nordvpn-myinstance' (based on .env)
    container_name: tailnord-nordvpn-${INSTANCE_NAME}
    hostname: tailnord-nordvpn
    entrypoint: [
      '/scripts/nordvpn_up.sh'
    ]
    restart: always
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.forwarding=1
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      - NORDVPN_TOKEN=${NORDVPN_TOKEN}
      - NORDVPN_ENDPOINT=${NORDVPN_ENDPOINT}
      - NORDVPN_TECHNOLOGY=${NORDVPN_TECHNOLOGY}
      - NORDVPN_OPENVPN_PROTOCOL=${NORDVPN_OPENVPN_PROTOCOL}
      - IP_SUBNET=${IP_SUBNET} # Subnet for internal container routing
      - ENV_NETWORK_PORTS=4164/udp # Allow Tailscale's UDP port through NordVPN's internal firewall
    volumes:
      - "/dev/net/tun:/dev/net/tun"
      - "./nordvpn/scripts:/scripts"
    cap_add:
      - net_admin
      - sys_module
    networks:
      tailnord-net:
        ipv4_address: ${IP_NORDVPN}

networks:
  tailnord-net:
    enable_ipv6: false
    ipam:
      config:
        - subnet: ${IP_SUBNET} # Network subnet for the Docker bridge network

